# Vakao UI 组件库 PNPM 工作区配置文件
#
# 此文件定义了 PNPM 工作区的包管理结构，用于管理多包项目。
# 工作区允许在单个仓库中管理多个相关的包，并在它们之间共享依赖。
#
# 主要优势：
# - 统一依赖管理：所有包共享相同版本的依赖
# - 高效的磁盘使用：避免重复安装相同的依赖
# - 简化开发流程：可以在包之间建立本地链接
# - 版本同步：确保所有包使用兼容的依赖版本
#
# 工作区结构说明：
# ├── packages/          # 组件库核心包目录
# │   ├── components/    # UI 组件包
# │   ├── hooks/         # 组合式 API 包
# │   ├── utils/         # 工具函数包
# │   ├── styles/        # 样式包
# │   └── types/         # 类型定义包
# └── docs/              # 文档站点包

packages:
  # 组件库核心包
  # 包含所有组件库相关的子包：组件、工具、样式等
  # 使用通配符 ** 匹配 packages 目录下的所有子目录
  - packages/**
  
  # 文档站点包
  # 基于 VitePress 构建的组件库文档和演示站点
  # 独立管理文档相关的依赖和构建配置
  - docs
